# Platform ressource
axa_whapi_platform_new:
    pattern:  /platforms
    defaults: { _controller: AxaWhapiBundle:Platform:post, _format: ~ }
    requirements:
        _method: POST

axa_whapi_platform_get:
    pattern:  /platforms/{id}
    defaults: { _controller: AxaWhapiBundle:Platform:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

axa_whapi_platform_update:
    pattern:  /platforms/{id}
    defaults: { _controller: AxaWhapiBundle:Platform:update, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"


# Vm ressource
axa_whapi_vm_update:
    pattern:  /vm/{id}
    defaults: { _controller: AxaWhapiBundle:VM:update, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"


# VmQueue ressource
axa_whapi_vmqueue_get:
    pattern:  /vmqueue/{ip}
    defaults: { _controller: AxaWhapiBundle:VmQueue:get, _format: ~ }
    requirements:
        _method: GET

