axa_whapi_homepage:
    path:     /hello/{name}
    defaults: { _controller: AxaWhapiBundle:Default:index }

axa_whapi_offer_list:
    path:     /offer
    defaults: { _controller: AxaWhapiBundle:Offer:list }
    requirements:
        _method:  GET

axa_whapi_platform_create:
    path:     /platform
    defaults: { _controller: AxaWhapiBundle:Platform:create }
    requirements:
        _method:  POST
