parameters:
#    axa_whapi.example.class: Axa\Bundle\WhapiBundle\Example

services:
#    axa_whapi.example:
#        class: %axa_whapi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
