<?php

namespace Axa\Bundle\WhapiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StackRepository extends EntityRepository
{
}
