<?php

namespace Axa\Bundle\WhapiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Axa\Bundle\WhapiBundle\Exception\DuplicateUserException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Persist the User
     *
     * @param User $user
     */
    public function persist(User $user)
    {
        $this->_em->persist($user);
        $this->_em->flush();
    }

    /**
     * Find or Create a new User
     *
     * @param string $userEmail the user email
     * @param boolean $persist whether the user should be persisted or not. Default to false
     * @return User|null|object
     * @throws \Axa\Bundle\WhapiBundle\Exception\DuplicateUserException
     */
    public function findOneByEmailOrCreate($userEmail, $persist = false)
    {
        if (! $user = $this->findOneBy(array("email" => $userEmail))) {
            $user = new User();
            $user->setEmail($userEmail)
                ->setUid($userEmail . '-' . uniqid());
        }

        if ($persist) {
            $this->persist($user);
        }

        return $user;
    }
}
